name: PythonTest

on: [push]

jobs:
  build:
    runs-on: Ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9.1'
        architecture: 'x64'
    - name: build
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install pylint
        pylint filename_class.py
        pylint filename_java.py
